# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)


env:
  global:
    - CODECOV_TOKEN="f770e729-5e68-497f-ba5c-ff82edde97dc"

# Отправлять уведомление на почту maksimus.s@mail.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -maksimus.s@mail.ru
    on_success: never # default: change
    on_failure: always # default: always